//! Latency and throughput metrics.
//!
//! Designed for low overhead: atomic counters and optional latency histograms.
//! The UI and monitoring can sample these values at intervals.

use std::sync::atomic::{AtomicU64, Ordering};

/// Central metrics store. All fields are atomic for lock-free reads.
#[derive(Debug, Default)]
pub struct Metrics {
    /// Number of market data messages processed.
    pub feed_messages: AtomicU64,
    /// Number of order book updates applied.
    pub book_updates: AtomicU64,
    /// Number of signals generated by strategies.
    pub signals_generated: AtomicU64,
    /// Number of orders approved by risk.
    pub orders_approved: AtomicU64,
    /// Number of orders submitted to exchange.
    pub orders_submitted: AtomicU64,
    /// Number of fills received.
    pub fills: AtomicU64,
    /// Last feed-to-processing latency in microseconds (stub: set by feed handler).
    pub latency_feed_us: AtomicU64,
}

impl Metrics {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn inc_feed_messages(&self) {
        self.feed_messages.fetch_add(1, Ordering::Relaxed);
    }

    pub fn inc_book_updates(&self) {
        self.book_updates.fetch_add(1, Ordering::Relaxed);
    }

    pub fn inc_signals(&self) {
        self.signals_generated.fetch_add(1, Ordering::Relaxed);
    }

    pub fn inc_approved(&self) {
        self.orders_approved.fetch_add(1, Ordering::Relaxed);
    }

    pub fn inc_submitted(&self) {
        self.orders_submitted.fetch_add(1, Ordering::Relaxed);
    }

    pub fn inc_fills(&self) {
        self.fills.fetch_add(1, Ordering::Relaxed);
    }

    pub fn set_latency_feed_us(&self, us: u64) {
        self.latency_feed_us.store(us, Ordering::Relaxed);
    }

    pub fn feed_messages(&self) -> u64 {
        self.feed_messages.load(Ordering::Relaxed)
    }

    pub fn latency_feed_us(&self) -> u64 {
        self.latency_feed_us.load(Ordering::Relaxed)
    }
}
